### ISSUE TITLE
fix ocaml.5.0.0 ci (jsoo test error)

### ISSUE THREAD

**Issue by haochenx** [kxcteam/kxclib-ocaml#32]
relevant error log (excerpt of https://github.com/kxcteam/kxclib-ocaml/actions/runs/4254986177/jobs/7402000342):
```
Full test results in `/__w/kxclib-ocaml/kxclib-ocaml/_build/default/unit_test/_build/_tests/Datecode_unit_tests'.
Test Successful in 0.007s. 111 tests run.
File "jsoo/unit_test/dune", line 17, characters 0-[122](https://github.com/kxcteam/kxclib-ocaml/actions/runs/4254986177/jobs/7402000342#step:9:123):
17 | (rule
18 |  (action (run %{bin:node} %{deps}))
19 |  ; (deps ./jsoo_unit_tests.js)
20 |  (deps ./jsoo_unit_tests.bc.js)
21 |  (alias runtest))
(cd _build/default/jsoo/unit_test && /usr/local/bin/node jsoo_unit_tests.bc.js)
/__w/kxclib-ocaml/kxclib-ocaml/_build/default/jsoo/unit_test/jsoo_unit_tests.bc.js:4379
       throw err}
       ^

TypeError: runtime.caml_unix_gethostname is not a function
    at gethostname (/__w/kxclib-ocaml/kxclib-ocaml/_build/default/jsoo/unit_test/jsoo_unit_tests.bc.js:47958:47)
    at caml_call1 (/__w/kxclib-ocaml/kxclib-ocaml/_build/default/jsoo/unit_test/jsoo_unit_tests.bc.js:57139:28)
    at /__w/kxclib-ocaml/kxclib-ocaml/_build/default/jsoo/unit_test/jsoo_unit_tests.bc.js:58905:10
    at Object.<anonymous> (/__w/kxclib-ocaml/kxclib-ocaml/_build/default/jsoo/unit_test/jsoo_unit_tests.bc.js:62469:3)
    at Module._compile (node:internal/modules/cjs/loader:[125](https://github.com/kxcteam/kxclib-ocaml/actions/runs/4254986177/jobs/7402000342#step:9:126)4:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:[130](https://github.com/kxcteam/kxclib-ocaml/actions/runs/4254986177/jobs/7402000342#step:9:131)8:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by haochenx** [comment]
fixed in https://github.com/kxcteam/kxclib-ocaml/commit/f3cc27a051cdcf6b272255a2b178772ae8a149db
